# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb428eb3194a7dad8359dad4b7c2962c7c9451ae565682949b03ce8d82442e1941d14cd427d00592c03499feadd5c82d68343d1bcb68a0bdd7a38a4a0d436463

test:
  secret_key_base: e86924940d627550dc188d220af925072bbfe41b0ced4dc1fd15c827ea88e3009dfc9695b18b57a96babc7bb2b5c98535c6dfdca9f05cc61ba72975da0107961

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
